### ISSUE TITLE
Errors about Centrality and CircosPlot

### ISSUE THREAD

**Issue by ytokunaga-giga** [msraredon/Connectome#1]
Hello,

I tried to follow the workflow on the website in below using demo data.
https://msraredon.github.io/Connectome/articles/01%20Connectome%20Workflow.html

and had two errors.
One is Centrality function. I tried this command

Centrality(panc8.con2,
           modes.include = NULL,
           min.z = NULL,
           weight.attribute = 'weight_sc',
           group.by = 'mode')

and got an error.
_not working, Error in cells[[j]] : subscript out of bounds_

The second is CircosPlot that is last command in the tutorial.
CircosPlot(panc8.con2,min.z=1,lab.cex = 0.4, gap.degree = 0.1)

and it said,
_Error in FilterConnectome(connectome, remove.na = T, min.z = min.z, ...) : 
  unused argument (gap.degree = 0.1)_

Then I tried without gap.degree = 0.1,
CircosPlot(panc8.con2,min.z=1,lab.cex = 0.4)

and then the error was
_Error: Maybe your `gap.degree` is too large so that there is no space to allocate
sectors._

Is it possible to solve them? 
Thank you.

**Comment by msraredon** [comment]
I cannot replicate either of these errors on my machine, but you are not the first person to bring up the first error, so I would like to identify and fix, if possible. Two questions:

1) Can you produce the exact code you are using to get these errors?
2) Can you confirm how many edges are currently in your panc8.con2 object? I suspect this may be the issue in both errors. 

S

**Comment by ajwilk** [comment]
I've also run into both of these issues and may have some ideas on the cause: 

1. Error in ```CircosPlot```: it appears that ```gap.degree``` is no longer an accepted argument in ```CircosPlot``` and gets passed to ```FilterConnectome``` where it has nowhere to go. It seems this argument has been replaced by ```small.gap``` and ```big.gap```, whose defaults are 1 and 10, respectively. When plotting a connectome with many edges, these values must be decreased to avoid the error. (There's some inconsistency on the accepted args in the documentation for ```CircosPlot```)
2. Error in ```Centrality```: originates from this line
```
  cells <- as.character(unique(union(levels(master_sub$source), 
                                     levels(master_sub$target))))
```
However, the ```source``` and ```target``` columns of the connectome are stored as character vectors, so ```levels``` returns NULL for each.

**Comment by msraredon** [comment]
@ajwilk @ytokunaga-giga thank you both very much for pointing these out. I have (I think) fixed both bugs.  Please re-download the master branch / reinstall / restart R and let me know if these are still happening. Both of these are hold-overs from earlier drafts of the software. Not sure exactly why they don't replicate in my environment.

Thanks!

S
