### ISSUE TITLE
Centrality "Hub/Authenticity Score" Legend

### ISSUE THREAD

**Issue by MatthewJShannon** [msraredon/Connectome#10]
Hello,

I am currently using the Connectome package to assess cell-cell signaling networks in my 10X single-cell dataset. I am in the process of plotting these results using your centrality function. One thing I noticed in your paper [https://doi.org/10.1038/s41598-022-07959-x] is that in figure 2B you include a legend for "Hub/Authority Score". However, I am unable to find a way to generate this legend following your published vignettes/GitHub R code.

Any assistance on how to plot this information would be much appreciated.

Thank you in advance,

Matthew

**Comment by msraredon** [comment]
This legend was custom drawn in Adobe Illustrator for publication. A similar legend can be created using ggplot2, see for details: https://stackoverflow.com/questions/59093011/how-to-customize-the-content-of-a-legend-of-a-dotplot-with-ggplot2

Hope this helps.
S
