### ISSUE TITLE
CreateConnectome error

### ISSUE THREAD

**Issue by sailseem** [msraredon/Connectome#9]
Dear,
   When i excute 
con_connect <- NormalizeData(con_connect)
con_connect <- ScaleData(con_connect,features = genes)
con_connect<- CreateConnectome(con,species = 'mouse',assay = "RNA",
                                 min.cells.per.ident = 10,p.values = F,calculate.DOR = F)
it returns errors:

Finished calculating percentage expressing RNA for cluster Mono 1
Finished calculating percentage expressing RNA for cluster cDC1
Finished calculating percentage expressing RNA for cluster cDC2
Finished calculating percentage expressing RNA for cluster Neutrophils

Generating Connectome
  |                                                                                         |   0%Error in `[.data.frame`(cluster.avgs.scale.df.lig, , sources[i]) : 
  undefined columns selected
In addition: Warning message:
In PseudobulkExpression(object = object, pb.method = "average",  :
  Exponentiation yielded infinite values. `data` may not be log-normed.

Can you help me with it? Thanks

**Comment by msraredon** [comment]
Sorry to have not responded to this until now. This is likely an error in the data format or structure when input into `CreateConnectome`. If you send reproducible code I can help troubleshoot.

**Comment by ZiDa20** [comment]
Hi, I am also experiencing the same issue:  Error in `[.data.frame`(cluster.avgs.scale.df.lig, , sources[i]) : undefined columns selected. 
Did you manage to find a reason for this ? I am using Seurat 4.1.1

**Comment by msraredon** [comment]
If you send reproducible code I can try to trouble shoot this on my end. Ideally using publicly available data, either from SeuratData or a private/publicly posted source so I can replicate exactly. I haven't encountered this before, so I'm not sure what's up without seeing it directly...

**Comment by msraredon** [comment]
Got it figured out.  You need to set the cell type identities first, as follows:

library(dplyr)
library(Seurat)
library(patchwork)
library(Connectome)
library(sessioninfo)
library(SeuratData)

# Load data
pbmc <- LoadData('pbmc3k')

# Process Data
pbmc <- NormalizeData(pbmc)
connectome.genes <- union(Connectome::ncomms8866_human$Ligand.ApprovedSymbol,Connectome::ncomms8866_human$Receptor.ApprovedSymbol)
genes <- connectome.genes[connectome.genes %in% rownames(pbmc)]
pbmc <- ScaleData(pbmc,features = genes)

# Set Identitities to cell types
table(Idents(pbmc))
Idents(pbmc) <- pbmc$seurat_annotations
table(Idents(pbmc))

# run Connectome
tryCatch({
  pbmc.con <- CreateConnectome(pbmc,
                               species = 'human',
                               min.cells.per.ident = 75,
                               p.values = F,
                               calculate.DOR = F)}, 
  error=function(cond) {print(cond)})

**Comment by junjieahaha** [comment]
I encountered the same problem. The reason for the error is that there are  "\_"  in Idents or celltype you named, but Seurat AverageExpression will replace "\_" to "-" or  something like that. So i added the code to CreateConnectome function and solved the problem.
colnames(cluster.avgs) <- str_replace_all(colnames(cluster.avgs),"\-","\_")
colnames(cluster.avgs.scale) <- str_replace_all(colnames(cluster.avgs.scale),"\-","\_")
